### ISSUE TITLE
jquery awesome cursor now working in Google Chrome Browser 

### ISSUE THREAD

**Issue by truetesterphp** [jwarby/jquery-awesome-cursor#11]
Hi jwarby,

jquery awesome cursor now working in Google Chrome Browser.

i have share my code here: https://drive.google.com/file/d/0B9xXyPnZ_WXuLWtIbTBtOEMyOWM/view?usp=sharing

please check this code. if any issue in this code then please let me know.

Thanks

**Comment by jwarby** [comment]
Hi @truetesterphp, I can't see any changes to the code in the zip file you linked to, and the plugin was already working fine in Chrome.  Can you explain exactly what the issue is, and what you were trying to achieve?  Thanks
