### ISSUE TITLE
Weird quote bug on my chrome

### ISSUE THREAD

**Issue by cauerego** [jwarby/jquery-awesome-cursor#14]
Most cursors will show in quotes. The iframe one in particular gets really big:

![screenshot](https://www.dropbox.com/s/sner6vp47b89itm/Screenshot%202015-05-08%2016.24.19.png?dl=1)

(this was a [bit harder to screenshot](http://apple.stackexchange.com/a/122254/1174) than I'd hope to!)

**Comment by jwarby** [comment]
Hi @cauerego, I can't rep this issue in Chrome or Firefox.  There was a very similar issue in Firefox a while back though (#10).  I'm assuming the fix will be pretty much the same, so I'll push a branch later that you can then test on your machine.

Also, what version of Chrome are you on?  For reference, my version is 42.0.2311.90.

**Comment by cauerego** [comment]
Right now it's 43.0.2357.52 beta. I don't even recall why I'm using beta...

It does look a very similar bug indeed. This doesn't happen on Safari, so probably it is related to being a beta chrome after all.

**Comment by jwarby** [comment]
Do you have a non-beta version to test on?

I tried Chrome Canary, beta and stable on Windows and all were fine (I think all of them were at v42.* though - in Linux atm so can't check).

**Comment by cauerego** [comment]
Nope, sorry. And I'm on a mac.

If you really want me to troubleshoot this further I can look into it later on. But if it's just for myself, I'm good. Ended up giving up on it thanks to issue #9  ;)

**Comment by j5vii** [comment]
I'm having this problem under OS X Chrome and Firefox as well.  I will look at issue #9 to see what help might be there...

**Comment by cauerego** [comment]
@j5vii I believe it's completely non related. I just mentioned it because that was the one that made me giving up on using jquery awesome and so going forward here became moot for me.

**Comment by j5vii** [comment]
there's a branch called issue-gh-14 ... I'm using that branch and things are working for me.

**Comment by jwarby** [comment]
Hi @j5vii, @cauerego.  My Chrome installation has updated to v43 and I'm seeing the same issue now.  As I can now test it properly, I will merge issue-gh-14 in and cut a new release this week.

Thanks for your help!
