### ISSUE TITLE
Composite cursors

### ISSUE THREAD

**Issue by jwarby** [jwarby/jquery-awesome-cursor#7]
A nice-to-have feature would be composite cursors, a la stacked icons in FontAwesome.  However, this might be difficult to implement, and is probably not worth considering further unless there is a demand for it.

**Comment by jakedowns** [comment]
I'd use this. ^_^ thanks for a handy plugin anyway

**Comment by jwarby** [comment]
Hey @jakedowns! I'm unlikely to have any spare time to look at this for awhile, so if you wanted to have a crack at it and submit a pull request you're more than welcome to :)

If so let me know and I can re-open this issue.
